name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Install Qt
        uses: sudo apt-get install -y qtbase5-dev

      - name: Configure CMake
        run: cmake .

      - name: Build All Targets
        run: make all

      - name: Run Unit Tests
        run: |
          make BtsApplicationUT && ./BTS/Tests/Application/BtsApplicationUT
          make COMMON_UT && ./COMMON/Tests/CommonUT
          make UeApplicationUT && ./UE/Tests/UeApplicationUT

      - name: Run Static Analysis (cppcheck)
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --error-exitcode=1 --inconclusive --quiet .

      - name: Run Code Formatting Check (clang-format)
        run: |
          sudo apt-get install -y clang-format
          find . -iname "*.h" -o -iname "*.cpp" | xargs clang-format -i
          git diff --exit-code

      - name: Run Memory Checks (Valgrind)
        run: |
          sudo apt-get install -y valgrind
          valgrind --leak-check=full --error-exitcode=1 ./BTS/Tests/Application/BtsApplicationUT
