name: Clang Format Check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ClangFormat
        run: sudo apt update && sudo apt install -y clang-format

      - name: Run ClangFormat
        run: |
          find . -iname '*.cpp' -o -iname '*.h' | xargs clang-format -i

      - name: Check for formatting changes
        run: |
          if ! git diff --exit-code; then
            echo "Code is not formatted correctly! Please run clang-format locally."
            exit 1
          fi
